# 这个是开发环境的配置文件

# 配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/onlinemusic?characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

    #配置springboot上传文件的大小，默认每个文件的配置最大为15Mb，单次请求的文件的总数不能大于100Mb
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB


# 开启 MyBatis SQL 打印
logging:
  level:
    com:
      example:
        demo: debug



# 配置mybatis xml 的保存路径
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 音乐上传的地址
#音乐上传后的路径
music_local_path: C:/work/local/music1

